# Generated by Django 5.2.8 on 2026-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
