# Generated by Django 5.2.8 on 2025-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_verified_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
