# Generated by Django 5.2.8 on 2026-01-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_active_role_delete_userroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavater',
            name='avater_uri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
