# Generated by Django 5.2.8 on 2025-12-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
