# Generated by Django 5.2.8 on 2025-12-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
