# Generated by Django 5.2.8 on 2025-12-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_is_active_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='black_listed_tokens',
        ),
    ]
