# Generated by Django 5.2.8 on 2025-12-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_certificates_name_alter_passwordreset_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
    ]
