# Generated by Django 5.2.8 on 2026-01-07 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('class_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.CharField(max_length=255)),
                ('invite_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('is_assigned', models.BooleanField(default=False, help_text='Assign class to another user')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(help_text='class_room_members', related_name='classroom_memebers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='classroom_supervisor', on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'classrooms',
                'db_table': 'classroom',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomInvite',
            fields=[
                ('classroom_invite_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('token', models.CharField(editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app_classroom.classroom')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_invite',
            },
        ),
        migrations.CreateModel(
            name='ClassroomMembership',
            fields=[
                ('classroom_membership_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('TEACHER', 'teacher'), ('TEACHING_ASSISTANT', 'teaching_assistant'), ('STUDENT', 'student')], db_index=True, default='STUDENT', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memebership', to='app_classroom.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memebership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_membership',
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('join_request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='app_classroom.classroom')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responded_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'join_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_active'], name='is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_deleted'], name='deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['invite_code'], name='invite_code_idx'),
        ),
        migrations.AddIndex(
            model_name='classroominvite',
            index=models.Index(fields=['email'], name='email_idx_class_invite'),
        ),
        migrations.AddIndex(
            model_name='classroominvite',
            index=models.Index(fields=['accepted'], name='accepted_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroommembership',
            constraint=models.UniqueConstraint(fields=('user', 'classroom'), name='unique_user_classroom'),
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(fields=('user', 'classroom'), name='unique_user_classroom_request'),
        ),
    ]
